version: '3.8'
services:
  stable-diffusion-webui:
    image: wuxiami/myvps-stable-diffusion-webui:latest
    ports:
      - "7860:7860"
    volumes:
      - ./data:/opt/stable-diffusion-webui/data
    restart: unless-stopped

